version: '3'

services:

  server:
    container_name: 'heroku-laravel-server'
    image: nginx
    restart: on-failure
    ports:
      - 880:80
    volumes:
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv:cached
    depends_on:
      - php-fpm

  php-fpm:
    container_name: 'heroku-laravel-php-fpm'
    build: ./docker/php-fpm
    restart: on-failure
    volumes:
      - ./:/srv:cached

